name: TEST

on: [pull_request]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Run Test
      run: xcodebuild test -scheme SwiftUISample -destination 'platform=iOS Simulator,name=iPad (8th generation)' -resultBundlePath TestResults
    - uses: kishikawakatsumi/xcresulttool@v1.0.1
      with:
        path: TestResults.xcresult
      if: always()
